import type { Metadata } from "next";
import { Roboto, Archivo } from "next/font/google";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets:["latin"]
})

const archivo = Archivo({
  variable: "--font-archivo",
  subsets:["latin"]
})

export const metadata: Metadata = {
  title: "QRme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${archivo.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
